Bochen.FullStack.BudgetTracker/Controllers/ExpendituresController.cs
using ApplicationCore.Models.Request;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bochen.FullStack.BudgetTracker.Controllers
{
    public class ExpendituresController : Controller
    {
        private readonly IExpenditureService _expenditureService;
        private readonly ICurrentUserService _currentUserService;

        public ExpendituresController(IExpenditureService expenditureService, ICurrentUserService currentUserService)
        {
            _expenditureService = expenditureService;
            _currentUserService = currentUserService;
        }

        [HttpGet]
        public IActionResult Add()
        {
            if(_currentUserService.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(ExpenditureRequestModel model)
        {
            var income = await _expenditureService.AddExpenditure(model);
            return LocalRedirect("~/");
        }
        [HttpGet]
        public IActionResult Update()
        {
            if (_currentUserService.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Update(ExpenditureRequestModel model)
        {
            var income = await _expenditureService.UpdateExpenditure(model);
            return LocalRedirect("~/");
        }

        [HttpGet]
        public IActionResult Delete()
        {
            if (_currentUserService.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(ExpenditureRequestModel model)
        {
            await _expenditureService.DeleteExpenditure(model);
            return LocalRedirect("~/");
        }
    }
}

Bochen.FullStack.BudgetTracker/Controllers/IncomesController.cs
using ApplicationCore.Models.Request;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bochen.FullStack.BudgetTracker.Controllers
{
    public class IncomesController : Controller
    {
        private readonly IIncomeService _incomeService;
        private readonly ICurrentUserService _currentUserService;

        public IncomesController(IIncomeService incomeService, ICurrentUserService currentUserService)
        {
            _incomeService = incomeService;
            _currentUserService = currentUserService;
        }

        [HttpGet]
        public IActionResult Add()
        {
            if (_currentUserService.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(IncomeRequestModel model)
        {
            var income = await _incomeService.AddIncome(model);
            return LocalRedirect("~/");
        }
        [HttpGet]
        public IActionResult Update()
        {
            if (_currentUserService.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Update(IncomeRequestModel model)
        {
            await _incomeService.UpdateIncome(model);
            return LocalRedirect("~/");
        }

        [HttpGet]
        public IActionResult Delete()
        {
            if (_currentUserService.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
       [HttpPost]
       public async Task<IActionResult> Delete(IncomeRequestModel model)
        {
            await _incomeService.DeleteIncome(model);
            return LocalRedirect("~/");
        }
    }
}

Bochen.FullStack.BudgetTracker/Controllers/UsersController.cs
using ApplicationCore.Models.Request;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using ApplicationCore.Entities;
using ApplicationCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bochen.FullStack.BudgetTracker.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService _userService;
        private readonly ICurrentUserService _currentUserService;

        public UsersController(IUserService userService, ICurrentUserService currentUserService)
        {
            _userService = userService;
            _currentUserService = currentUserService;
        }
        public async Task<IActionResult> Details(int id)
        {
            var user = await _userService.GetUserDetailsById(id);
            return View(user);
        }

        [HttpGet]
        public IActionResult Delete()
        {
            if (_currentUserService.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(UserUpdateRequestModel model)
        {
            await _userService.DeleteUser(model);
            return LocalRedirect("~/");
        }
        [HttpGet]
        public IActionResult Update()
        {
            if (_currentUserService.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Update(UserUpdateRequestModel model)
        {
            await _userService.UpdateUser(model);
            return LocalRedirect("~/");
        }
    }
}

Bochen.FullStack.BudgetTracker/Views/Users/Delete.cshtml
@model ApplicationCore.Models.Request.UserUpdateRequestModel
@{
    ViewData["Title"] = "Delete";
}

<h3>Delete User</h3>

<div class="row justify-content-center">
    <div class="col-md-4 ">
        <form asp-action="Delete" class="">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    Delete
                </button>
            </div>
        </form>
    </div>
</div>

Bochen.FullStack.BudgetTracker/Views/Users/Details.cshtml
@model ApplicationCore.Models.Response.UserDetailsResponseModel


@{
    ViewData["Title"] = "Details";
}
<div>
    <div class="row">
        <div class="col-md-5">
        </div>
        <div class="col-md-4" class="text-center">
            <div class="row">
                <h3>@Model.Fullname</h3>
            </div>
            <div class="row">
                <h4><span>@Model.Email</span></h4>
            </div>

        </div>

    </div>
</div>
<div>
    <div class="greenTable">
        <h5 class="center">Incomes</h5>

        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Amount</th>
                    <th>Description</th>
                    <th>Date</th>
                    <th>Remarks</th>
                </tr>
            
            </thead>
            <tbody>
                @foreach (var income in Model.Incomes)
                {
                <tr>
                    <td>@income.Id</td>
                    <td>&#36;@income.Amount</td>
                    <td>@income.Description</td>
                    <td>@income.IncomeDate</td>
                    <td>@income.Remarks</td>
                    <td>
                        <a asp-controller="Incomes" asp-action="Add" type="button" class="btn btn-info">Add</a>
                        <a asp-controller="Incomes" asp-action="Update" type="button" class="btn btn-warning">Update</a>
                        <a asp-controller="Incomes" asp-action="Delete" type="button" class="btn btn-danger">Delete</a>
                    </td>
                </tr>

                }
            </tbody>
        </table>

    </div>
    <div class="redTable">
        <h5 class="center">Expenditures</h5>

        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Amount</th>
                    <th>Description</th>
                    <th>Date</th>
                    <th>Remarks</th>
                </tr>
            
            </thead>
            <tbody>
                @foreach (var exp in Model.Expenditures)
                {
                <tr>
                    <td>@exp.Id</td>
                    <td>&#36;@exp.Amount</td>
                    <td>@exp.Description</td>
                    <td>@exp.ExpDate</td>
                    <td>@exp.Remarks</td>
                    <td>
                        <a asp-controller="Expenditures" asp-action="Add" type="button" class="btn btn-info">Add</a>
                        <a asp-controller="Expenditures" asp-action="Update" type="button" class="btn btn-warning">Update</a>
                        <a asp-controller="Expenditures" asp-action="Delete" type="button" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>

    </div>
</div>

Bochen.FullStack.BudgetTracker/Views/Users/Update.cshtml
@model ApplicationCore.Models.Request.UserRegisterRequestModel
@{
    ViewData["Title"] = "Update";
}

<h3>Update</h3>

<div class="row justify-content-center">
    <div class="col-md-4 ">
        <form asp-action="Update" class="">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input type="password" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fullname" class="control-label"></label>
                <input asp-for="Fullname" class="form-control" />
                <span asp-validation-for="Fullname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    Update
                </button>
            </div>
        </form>
    </div>
</div>